### PR TITLE
Fixing Deprecations for Atom 1.0

### PR DESCRIPTION
**Pull request by SeanSith**
Adjusted View calls to atom-space-pen-views, rebuilt config stanza, switched out
activationEvents for activationCommands.

### CODE REVIEW

**Comment by tjmehta** [comment]
Sweet thank you!

**Comment by mainameiz** [comment]
Hello, When it will be merged?

**Comment by tjmehta** [comment]
Sorry for the delay @SeanSith, pulling these now and adding you as a repo/package owner

**Comment by tjmehta** [comment]
Not sure how I add you as an apm module owner lmk if you do. I published your changes as 0.2.3

**Pull request merged**
